apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ 

replicas:
  - name: flaskapp-deployment
    count: 1
patches:
  - path: resource-limits.yaml
    target:
      kind: Deployment
      name: flaskapp-deployment
