apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

replicas:
- count: 3
  name: flaskapp-deployment
patches:
- path: resource-limits.yaml
  target:
    kind: Deployment
    name: flaskapp-deployment
images:
- name: mohamedtarek5/myflaskapp
  newTag: "26"
