all:
  hosts:
    controlplane-node:
      ansible_host: 10.0.2.253
      ansible_ssh_private_key_file: ~/.ssh/ec2_key.pem  
      ansible_ssh_common_args: >
        -o ProxyCommand="ssh -i ~/.ssh/ec2_key.pem -W %h:%p ubuntu@54.70.254.236"
    worker-node:
      ansible_host: 10.0.2.197
      ansible_ssh_private_key_file: ~/.ssh/ec2_key.pem  
      ansible_ssh_common_args: >
        -o ProxyCommand="ssh -i ~/.ssh/ec2_key.pem -W %h:%p ubuntu@54.70.254.236"

  children:
    controlplane:
      hosts:
        controlplane-node:
    worker:
      hosts:
        worker-node:

  vars:
    ansible_python_interpreter: /usr/bin/python3