all:
  hosts:
    controlplane-node:
      ansible_host: 10.0.2.233
      ansible_ssh_private_key_file: ~/.ssh/ec2_key.pem  # Key for private EC2
      ansible_ssh_common_args: >
        -o ProxyCommand="ssh -i ~/.ssh/ec2_key.pem -W %h:%p ubuntu@35.92.226.177"
    worker-node:
      ansible_host: 10.0.2.160
      ansible_ssh_private_key_file: ~/.ssh/ec2_key.pem  # Key for private EC2
      ansible_ssh_common_args: >
        -o ProxyCommand="ssh -i ~/.ssh/ec2_key.pem -W %h:%p ubuntu@35.92.226.177"

  children:
    controlplane:
      hosts:
        controlplane-node:
    worker:
      hosts:
        worker-node:

  vars:
    ansible_python_interpreter: /usr/bin/python3