apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml
- statefulset.yml
- pvc.yml
- ingress.yml

configMapGenerator:
- name: flaskapp-config
  literals:
  - MYSQL_DATABASE_DB=BucketList
  - MYSQL_DATABASE_HOST=db-service
